[project]
name = "cloudflare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["nodriver>=0.48.0"]

[project.scripts]
cloudflare = "cloudflare:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"


[project.optional-dependencies]

ml = ["opencv-python"]
