[tool.uv.sources]
telegram = { workspace = true }
cloudflare = { workspace = true }
pumpfun = { workspace = true }
pumpportal = { workspace = true }
shared-lib = { workspace = true }
rpc = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/telegram",
    "packages/cloudflare",
    "packages/shared_lib",
    "packages/pumpfun",
    "packages/pumpportal",
    "packages/rpc",
]
[dependency-groups]
dev = ["pytest", "pytest-asyncio", "ruff"]
