[project]
name = "shared-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "christianfm10", email = "christian.flores@dekoding.pe" }]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.0,<0.29.0",
    "pydantic>=2.12.0,<2.13.0",
    "python-dotenv>=1.2.0,<1.3.0",
]

[project.scripts]
shared-lib = "shared_lib:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
